### ISSUE TITLE
Error with "com.google.android.material.textfield.TextInputLayout>

### ISSUE THREAD

**Issue by triengineervn** [triengineervn/WavesOfFood#1]
FATAL EXCEPTION: main

![Screenshot 2024-09-19 153657](https://github.com/user-attachments/assets/b079aa46-eaa6-4c1e-9d9e-9d75c23ced67)

Process: com.example.wavesoffood, PID: 22000
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.wavesoffood/com.example.wavesoffood.activities.AddLocationActivity}: android.view.InflateException: Binary XML file line #26 in com.example.wavesoffood:layout/activity_add_location: Binary XML file line #26 in com.example.wavesoffood:layout/activity_add_location: Error inflating class com.google.android.material.textfield.TextInputLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #26 in com.example.wavesoffood:layout/activity_add_location: Binary XML file line #26 in com.example.wavesoffood:layout/activity_add_location: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: android.view.InflateException: Binary XML file line #26 in com.example.wavesoffood:layout/activity_add_location: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at com.example.wavesoffood.databinding.ActivityAddLocationBinding.inflate(ActivityAddLocationBinding.java:60)
	at com.example.wavesoffood.databinding.ActivityAddLocationBinding.inflate(ActivityAddLocationBinding.java:54)
	at com.example.wavesoffood.activities.AddLocationActivity$binding$2.invoke(AddLocationActivity.kt:11)
	at com.example.wavesoffood.activities.AddLocationActivity$binding$2.invoke(AddLocationActivity.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.example.wavesoffood.activities.AddLocationActivity.getBinding(AddLocationActivity.kt:10)
	at com.example.wavesoffood.activities.AddLocationActivity.onCreate(AddLocationActivity.kt:15)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)

**Comment by triengineervn** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/textView5"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/prompt_add_location"
        android:textAppearance="@style/TextAppearance.WavesOfFood.Subtitle"
        android:layout_marginTop="@dimen/space_xl"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        style="@style/CustomStyle.WavesOfFood.TextInput"
        android:layout_width="match_parent"
        android:layout_height="@dimen/text_input"
        android:layout_marginTop="@dimen/space_m"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView5">

        <AutoCompleteTextView
            android:id="@+id/listOfLocation"
            android:textAppearance="@style/TextAppearance.WavesOfFood.Body"
            android:drawableEnd="@drawable/arrow_circle_down"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            style="@style/CustomStyle.WavesOfFood.NoUnderlineAutoCompleteTextView"
            android:text="@string/prompt_add_location" />
    </com.google.android.material.textfield.TextInputLayout>

    <TextView
        android:id="@+id/textView6"
        android:textAppearance="@style/TextAppearance.WavesOfFood.Caption"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/space_l"
        android:layout_marginHorizontal="@dimen/activity_horizontal_margin"
        android:text="@string/prompt_choose_location"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by triengineervn** [comment]
**Remove dependencies**
   
**Now, Perfect layout**

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        style="@style/CustomStyle.WavesOfFood.TextInput"
        android:layout_width="match_parent"
        android:layout_height="@dimen/space_xl"
        android:layout_marginTop="@dimen/space_xs"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView2">
    
      <AutoCompleteTextView
              android:id="@+id/listOfLocation"
              android:drawableEnd="@drawable/arrow_circle_down"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:hint="@string/prompt_add_location" />
    </com.google.android.material.textfield.TextInputLayout>

Style for Text Input

    <style name="CustomStyle.WavesOfFood.TextInput" 
        parent="Widget.Material3.TextInputLayout.OutlinedBox.ExposedDropdownMenu">
        <item name="android:background">@drawable/background_outline</item>
        <item name="endIconMode">none</item>
        <item name="hintEnabled">false</item>
        <item name="android:layout_marginHorizontal">@dimen/activity_horizontal_margin</item>
        <item name="boxStrokeWidth">0dp</item>
        <item name="boxStrokeWidthFocused">0dp</item>
    </style>
